<section style="text-align: justify;>
<h5><b>1. Información General</b></h5>
<ul>
<li>Bienvenid@s. Muchas gracias por acceder a nuestra plataforma (i.e. sitio web y/o aplicación móvil) de evaluación, promoción y venta de Vehículos Sustentables; ventana publicitaria de patrocinadores, sitio de adquisición de los productos de SAICOR, gratuitos y/o de paga, y realización de actividades comerciales entre los Usuarios de la Plataforma, (en adelante la "Plataforma").</li>
<li>La Plataforma es propiedad de Grupo Molina y Chaves, Sociedad Anónima, (en adelante "SAICOR") una empresa costarricense activa y debidamente registrada, según las leyes de la República de Costa Rica.</li>
<li>Contra registro del usuario, se le otorga un permiso no exclusivo, temporal, personalísimo e intransferible de acceso a la Plataforma, que no implica traslado de propiedad de contenidos, información y/o data alguna, ni de SAICOR, ni de terceros.</li>
<li>El registro en algunos casos puede ser realizado directamente por el Usuario, (usuarios de un vehículo automotor, particular o empresarial) hay otros casos donde los Usuarios (comerciantes de productos o servicios afines al sector automotriz), para registrarse, requieren previa autorización y deben ser registrados por parte de SAICOR.</li>
</ul>
<h5><b>2. De los presentes Términos y Condiciones</b></h5>
<ul>
<li>La aceptación pura y simple de los presentes términos y condiciones que se encuentran vigentes (en adelante los "TyC"), es un requisito obligatorio para el uso de la Plataforma; por ende, estos TyC aplican irrestrictamente, en lo que corresponda, a la evaluación, promoción y venta de Vehículos Sustentables, uso de la ventana publicitaria y publicaciones de carácter, público y/o privados, gratuitos y/o de paga, que se realicen a través de la Plataforma; a la facilitación de medios para la venta y/o distribución de productos y/o servicios de SAICOR y/o terceros; y en lo concerniente a generalidades, al uso en cualquier forma de la Plataforma y/o sus contenidos, (en adelante los "Usos").</li>
<li>De no estar usted de acuerdo con TyC aquí establecidos, sírvase pulsar el botón "No acepto" y dejar el sitio; por el contrario, de estar de acuerdo con todos ellos en su integralidad, deberá proceder a pulsar el botón "Acepto". Una vez pulsado el botón de "Acepto", se entenderá que el Usuario ha emitido su voluntad pura, simple e incondicional, de regirse enteramente y sin condiciones por lo aquí estipulado.</li>
<li>Entiéndase que SAICOR no obliga a ninguna persona física o jurídica a hacer uso de su Plataforma, a registrarse en su sitio, ni a aceptar sus TyC, de manera que al obligarse voluntariamente a hacerlo pulsando el botón de "Acepto", el usuario da muestra clara y evidente de su intención adoptar los TyC, sin objeción alguna.</li>
<li>SAICOR se reserva el derecho de modificar o enmendar, total o parcialmente, los presentes TyC, en cualquier momento y sin previo aviso, bastando solamente para ello, el publicar una nueva versión de éstos, de modo que una vez publicados, entrarán de inmediato en plena vigencia, sustituyendo los anteriores. Asimismo, el usuario entiende y acepta que los presentes TyC se ajustarán en lo concerniente, a los cambios normativos obligatorios que les apliquen. El Usuario entiende que es su responsabilidad revisar los TyC periódicamente, a fin de conocer plenamente la versión vigente.</li>
<li>Al aceptar los presentes TyC, el Usuario entiende y acepta que podrá recibir comunicaciones de SAICOR, o de quienes SAICOR determine, incluyendo, pero sin limitarse éstas, consultas, avisos, encuestas y/o notificaciones de cualquier índole.</li>
<li>SAICOR ofrece la facultad al Usuario de desafiliarse de las listas de destinatarios de comunicaciones y notificaciones; facultad que podrá ejercer deshabilitando desde su dispositivo móvil (Iphone y Android) o computador, la opción de notificaciones.</li>
<li>SAICOR se reserva el derecho de solicitar a ciertos Usuarios, el suscribir acuerdos escritos diferentes, ampliados y/o aclaratorios de lo aquí estipulado, como pautas publicitarias en el sitio web, arrendamiento de la plataforma, pero sin limitarse a estos, cuando lo considere propicio; circunstancia que informará al Usuario, por los medios que SAICOR así lo disponga.</li>
<li>En la sana administración de su Plataforma y en estricto apego al ordenamiento jurídico aplicable, SAICOR podrá ejercer mediante personas expresamente autorizadas para tales efectos, el monitoreo activo de todo el acontecer en su Plataforma. Esto con el fin de evitar ataques, pérdida o mala utilización de los recursos provistos; violaciones a los TyC, a las normas aplicables; así como accesos o acciones no autorizadas o ilegales, entre otras.</li>
<li> El Usuario entiende y acepta que de encontrar SAICOR violaciones o desacatos a sus TyC, a la normativa aplicable, y/o a las normas de la moral y las buenas costumbres, procederá a tomar las medidas administrativas, civiles, penales, procedimentales, y/o cautelares que estime convenientes y que le permita el ordenamiento jurídico, para solventar la situación.</li>
<li>Todo Usuario debe tener presente, que la Plataforma debe ser utilizada únicamente para los efectos legales previamente autorizados por SAICOR e intrínsecamente relacionados con los Usos previstos, así como para aquellos otros usos que SAICOR a su sola discreción, llegue expresamente a autorizar en el futuro. Cualquier otro uso comercial que pretenda hacer el Usuario, deberá recibir aprobación previa y por escrito de SAICOR.</li>
</ul>
<h5><b>3.Condiciones básicas del uso de la Plataforma</b></h5>

El Usuario entiende y acepta conscientemente lo siguiente:
<ul>
<li>El acceso a la Plataforma no le reportará al Usuario, ningún derecho de propiedad ni de explotación sobre ésta, ni sobre sus contenidos, elementos, data o información que en ella se encuentren, que no sea el de meramente utilizarlos de conformidad con los TyC aquí estipulados y dentro del marco de legalidad aplicable. Así, salvo estipulación expresa y en contrario emitida por escrito por SAICOR la data e información incluida en la Plataforma no podrá ser reproducida, copiada, cedida, traducida, transcrita, almacenada, ni de ninguna manera dispuesta, para efectos diversos a los expresamente permitidos por SAICOR
<li>El Usuario entiende y acepta que toda data e información que ingrese a la Plataforma y que éste ponga a disposición de SAICOR estará cubierta por una presunción de autorización, aplicable y defendible tanto a nivel nacional como internacional y que faculta a SAICOR a utilizarla de manera irrestricta en los términos de los TyC vigentes y según lo permita el ordenamiento jurídico aplicable.
<li>El Usuario podrá subir, ingresar o postear data e información a la Plataforma, que cumpla con los requisitos de ser legal, actual, veraz, exacta, y adecuada a los Usos autorizados por SAICOR y a los TyC vigentes.
<li>El Usuario entiende y acepta que a través de la Plataforma sólo podrá ser utilizada para los Usos estipulados por SAICOR. En cualquier caso, el Usuario garantiza que los datos e información que promociona, son reales, legales, y que están dentro de los parámetros aceptables, previamente definidos por el ordenamiento jurídico aplicable y por los TyC vigentes, y que además, se encuentra autorizado para su publicación.
<li>El Usuario que ingresa información o data a la Plataforma, tiene plena conciencia y autoriza expresamente, que dicha información sea utilizada por SAICOR, entre otros, para efectos de:</li>
</ul>
<b>o</b> Comprobar la seriedad de las intenciones del Usuario;
<br><b>o</b> Verificar la veracidad y exactitud de la información ingresada;
<br><b>o</b> Compartir aquella información destinada a ser compartida en virtud/con ocasión de las actividades y/o de los Usos previstos para la Plataforma y otros relacionados;
<br><b>o</b> Modificarla, promocionarla, traducirla, editarla, graficarla, parametrizarla, actualizarla, cambiarle el formato, reproducirla, y/o hacer trabajos derivados;
<br><b>o</b> Entregar la información a las autoridades cuando ello sea así requerido en virtud de mandato oficial emitido a los efectos;
<br><b>o</b> Construir perfiles de utilización de la Plataforma, perfiles estadísticos, de consumo, y/o de utilización de recursos;
<br><b>o</b> Realizar estudios de inteligencia de mercado;
<br><b>o</b> Enviar al Usuario boletines, encuestas, notificaciones y comunicados informativos;
<br><b>o</b> Enviar al Usuario boletines, encuestas, notificaciones y comunicados informativos;
<br><b>o</b> Realizar eventos propagandísticos;
<br><b>o</b> Levantar bases de datos, compilaciones, ficheros electrónicos, repositorios de imágenes, galerías de fotos u otros instrumentos similares;
<br><b>o</b> Utilizarla en procesos legales;
<br><b>o</b> Proteger derechos de los Usuarios, de SAICOR y/o de terceros;
<br><b>o</b> Utilizarla, tal cual o modificada, para fines de mercadeo, publicitarios y/o promocionales de SAICOR y/o de sus Aliados de Negocio (e.g. patrocinadores, contratistas, publicistas, socios comerciales);
<br><b>o</b> Analizarla para entender la forma de brindar un mejor servicio; y
<br><b>o</b> Para otras actividades relacionadas con las anteriores y/o derivadas de éstas.
<br><b>o</b> La autorización incluida en este inciso podrá ser revocada en cualquier momento por el Usuario, comunicándolo por escrito a la persona encargada por SAICOR para velar por la información (en adelante el "Tutor de la Información"), a la siguiente dirección legal@saicor.co.cr, donde también podrá el Usuario, ejercitar su derecho de rectificación, cancelación, supresión y/u oposición. El Usuario entiende y acepta que su eventual requerimiento en este sentido, no tiene efecto retroactivo; se ejecutará dentro del plazo de ley; y no aplica para transacciones o negociaciones que estén en proceso entre el Usuario y SAICOR, en el tanto éstas no hayan terminado de concretarse y se siga requiriendo la información.
<br><br>
<ul>
<li>El Usuario entiende y acepta que SAICOR no está obligado a utilizar, cargar, ni postear la data e información que se le proporciona y que SAICOR podrá, a su sola discreción, eliminar dicha data o información de la Plataforma, cuando considere que está duplicada; es confusa; es falsa; ilegal; no es consistente con los valores o principios que defiende SAICOR; es insultante; racista, discriminatoria, ofensiva, humillante; responde a intereses o está relacionada con actividades terroristas; va contra la moral y las buenas costumbres; propicia revueltas, desorden social, comisión de crímenes; hace apología de delitos; es información que el Usuario no tenía autorización de utilizar y/o no se ajusta a los intereses comerciales, ni a los objetivos de negocio de SAICOR. Asimismo, el Usuario entiende y acepta que el uso contrario a los TyC vigentes, podrá hacer que SAICOR decida eliminar cualquier tipo de información ingresada, incluso aquella almacenada en los Registros mismos del Usuario.
<li>El Usuario que desee subir y/o publicar por medio de la Plataforma, podrá incluir marcas, nombres comerciales, imágenes, signos distintivos, gráficos, archivos de audio y video, dibujos, fotografías, esquemas, ilustraciones, y vínculos a otros sitios, entre otros, siempre que éstos le pertenezcan y/o cuente previamente con autorización expresa emitida por el dueño de la propiedad intelectual, de los derechos de autoría, de patentes, derechos registrados, secretos comerciales o industriales y/u otros derechos conexos sobre los mismos, y/o por el encargado con poder suficiente de decisión sobre éstos. El Usuario, deberá poseer comprobante de dichos permisos y/o autorizaciones y ponerlos a disposición de SAICOR, cuando así se le requiera.
<li>El Usuario será responsable por todos sus actos y omisiones en el uso de la Plataforma. Así las cosas, el Usuario entiende claramente y acepta que los siguientes comportamientos son inaceptables, y que por ende, derivarán consecuencias para quien los lleve a cabo:
</ul>
<b>o</b> Injuriar, calumniar, desacreditar, ofender, agredir, insultar, amenazar o acosar a cualquier persona, sea ésta física o jurídica;
<br><b>o</b> Diseminar y propagar cadenas de mensajes (chain letters) o mensajes comerciales no solicitados;
<br><b>o</b> Transmitir información ilegal, falsa, obscena, pornográfica, discriminatoria, difamatoria; abusiva; ofensiva, vulgar, amenazante, o maliciosa;
<br><b>o</b> Poner en peligro la integridad de la información de SAICOR y/o la continuidad de las actividades la empresa;
<br><b>o</b> Hacer representaciones en nombre de SAICOR, que no han sido expresamente autorizadas;
<br><b>o</b> Dañar la reputación de SAICOR y/o de sus clientes;
<br><b>o</b> Diseminar, guardar, transmitir y/o copiar información o data, incluyendo, pero sin limitarse a software, gráficos, archivos, materiales u otros contenidos, capaces de infringir derechos de propiedad intelectual, de autoría, patentes, derechos registrados, secretos comerciales o industriales y/u otros derechos conexos pertenecientes a terceros;
<br><b>o</b> Dañar o amenazar el derecho a la privacidad de terceros y otros derechos de terceros;
<br><b>o</b> Crear falsas identidades o perfiles al registrarse en la Plataforma o impersonar a terceros;
<br><b>o</b> Crear falsas direcciones o cubrir el origen, identidad real o proveniencia de cualquier comunicación, notificación o mensaje;
<br><b>o</b> Exportar o importar cualquier contenido o mensaje en violación al ordenamiento jurídico, a los TyC vigentes y a las normas aplicables, y/o sin contar con los permisos, licencias y/o autorizaciones necesarias;
<br><b>o</b> Tratar de vulnerar los sistemas de seguridad de SAICOR
<br><b>o</b> Utilizar las claves y/o registros de otros Usuarios, aún con autorización de dichos Usuarios;
<br><b>o</b> Realizar ataques a otros sitios o plataformas, desde la Plataforma de SAICOR y realizar ataques a SAICOR desde cualquier plataforma o sistema;
<br><b>o</b> Diseminar, guardar o transmitir instrucciones dañinas o maliciosas, en todas sus formas y/o por cualesquier medio;
<br><b>o</b> Interferir, alterar o dañar la operación de los sistemas de SAICOR,
<br><b>o</b> Tratar de obtener información confidencial que no le corresponda;
<br><b>o</b> Llevar a cabo los siguientes comportamientos con respecto a personas menores de edad (en adelante "PME"):
<br><b>&nbsp;1.</b> Tratar de obtener o en efecto obtener información de PME;
<br><b>&nbsp;2.</b> Tratar de brindarles o en efecto brindarles, información perniciosa o inconveniente;
<br><b>&nbsp;3.</b> Tratar de inducirlos o efectivamente inducirlos a realizar, observar y/o participar en comportamientos inapropiados, dañinos o nocivos, así como en conductas ilícitas;
<br><b>&nbsp;4.</b> Tratar de causarles daño y/o dañarlos en cualquier sentido y/o de cualesquier forma;
<br><b>&nbsp;5.</b> Someterlos a explotación sexual o a cualquier tipo de explotación;
<br><b>&nbsp;6.</b> Utilizar la Plataforma para ingresar información que en cualesquier forma los victimice.
<br><b>o</b> SAICOR defiende y respeta en todo sentido los derechos de las PME, y desprecia todo comportamiento denigrante, humillante o dañino en contra de éstas, por lo que de encontrar que alguno de dichos comportamientos está siendo desarrollado o permitido por el Usuario en la Plataforma, tomará las acciones correspondientes para evitar que los mismos sigan ocurriendo, incluso al punto de enviar la información de los Usuarios involucrados, a las autoridades;
<br><b>o</b> Brindar instrucciones para la realización de conductas delictivas;
<br><b>o</b> Defraudar o tratar de defraudar y/o embaucar a otros Usuarios, o a SAICOR
<br><b>o</b> Cualquier otro comportamiento que a juicio de SAICOR, pueda poner en riesgo su estabilidad u objetivos de negocio.
<br><b>o</b> El Usuario entiende y acepta que la información y data ingresada, no está disponible al público, y no será entregada a terceros, a menos que SAICOR considere, a su sola discreción, que hay motivos suficientes que justifiquen dicha entrega. Así, será potestad de SAICOR decidir cuál información entrega y cuál no, dependiendo de las circunstancias que se le presenten.
<br><b>o</b> De conformidad con el punto 3.9. anterior, los Usuarios entienden y aceptan que la información (incluyendo, pero sin limitarse a dirección de correo electrónicos, número de cédula, direcciones, y números de teléfono, entre otros) no les será entregada a terceros por defecto, a menos que a juicio de SAICOR y/o según la circunstancia de que se trate, ésta deba entregárseles.
<br><b>o</b> El Usuario entiende y acepta que en caso que SAICOR tenga que enfrentar un proceso judicial y/o extrajudicial, en virtud de información o data ingresada a la Plataforma por el Usuario, así como en virtud del mal uso que el Usuario le de a la Plataforma misma o sus contenidos; será el Usuario involucrado, quien tenga que responder personal y directamente por todas las consecuencias que de su actuar u omisión deriven, incluso al punto de tener que cubrir por su cuenta y riesgo, con todos los costos y gastos que ello implique, incluyendo pero sin limitarse éstos, a la defensa legal de SAICOR cuando ella se requiera, así como las sumas a las que eventualmente ésta fuera condenada.
<br><br>
<h5>4. De la participación de SAICOR en las relaciones comerciales entre Usuarios de la Plataforma y/o terceros</h5>
<br>
<ul>
<li>El Usuario entiende y acepta que en la relación comercial que realicen entre Usuarios y/o terceros a través de la Plataforma, la participación de SAICOR, se limita únicamente a proveer una "ventana" para los Usos estipulados por SAICOR, no teniendo SAICOR responsabilidad alguna entre dichas relaciones comerciales que se realicen entre los Usuarios y/o terceros. SAICOR no pretende garantizar, y de hecho no lo hace, que los productos y/o servicios comercializados por los Usuarios a través de la Plataforma, vaya a realizarse; que se respeten horarios, precios, locaciones o ubicaciones previamente definidas o publicadas; no da fe de la calidad; no avala, apoya, o hace aseveración alguna respecto de las intenciones, la seriedad u otros, que afecten o beneficien las relaciones comerciales entre Usuarios y/o terceros.
<li>El Usuario entiende y acepta que SAICOR no es vendedor ni revendedor de productos y/o servicios de los Usuarios, sino que funge como un canal publicitario, de contacto y/o facilitador de la relación y transacción comercial, entre Usuarios y/o terceros, las acciones que se deriven de dichas relaciones comerciales serán solidariamente responsable los Usuarios y/o terceros implicados y nunca SAICOR.
</ul>

<h5><b>5. De las las formas de cobro</b></h5>
<ul>
<li>SAICOR no responde, sobre los estándares, medidas y/o políticas de seguridad de la información acogidas por los Cobradores; sobre el manejo que éstos le den a la información provista por el Usuario; sobre el uso que hayan de hacer del pago recibido; ni sobre los plazos o tiempos que se tarden gestionando los posibles reembolsos o reintegros al Usuario, si ello procediere. Así como tampoco da SAICOR, garantía alguna sobre las capacidades financieras de los Cobradores, ni sobre su solvencia económica y/o moral.
<li>Cada producto y/o servicio de SAICOR comprado por los Usuarios, en la Plataforma, como en sus puntos de venta, está sujeto a un cargo, éste cargo se está aceptando pagar al momento de aceptar los TyC, para el Uso de los productos y servicios de la Plataforma.
<li>El monto de cargo por servicio puede variar. El cargo por productos y/o servicios, refleja los gastos implicados en proporcionar un servicio de calidad para el comprador.
<li>El Comprador entiende y acepta que una vez que coloca su orden (en adelante la "Orden") y da curso al pago de productos y/o servicios en el sitio del Cobrador, la misma queda en firme, por ende, no se acepta posteriormente ningún cambio, reintegro o devolución que se pretenda hacer, a menos que SAICOR así lo autorice. 
<li>El Comprador entiende y acepta que todo cargo que se genere por costos de envío y/o relacionados, u otros cargos por servicios no está incluido dentro del Valor del Producto y/o servicio; y debe, por ende, cubrirlo éste. Los gastos y costos de envío al Comprador, no serán reembolsables en ningún caso.
<li>Los Usuarios entienden y aceptan que dado que SAICOR no tiene injerencia alguna sobre las relaciones comerciales que por medio de la Plataforma se realicen entre Usuarios y/o terceros, sobre su viabilidad; sobre la naturaleza de los mismos; sobre su organización, ni sobre las posibles cancelaciones que se puedan producir, y dado que la Plataforma genera gastos y costos de operación, incluso antes de que se llegue a concretar y/o cancelar una negociación, el Cargo por Productos y/o Servicios que corresponde a SAICOR es final y no está sujeto a devoluciones de ningún tipo, ni en ningún tiempo. Así, los Usuarios que realicen actividad comercial entre ellos, se abstendrán en todo momento de instaurar cualquier tipo de reclamos y/o acciones de cualesquier naturaleza contra SAICOR, en virtud de que entienden y aceptan que independientemente de lo que pase, y del tipo de relación que se pueda generar entre los Usuarios, el servicio de SAICOR está dado, desde el momento mismo en que pone a su disposición la Plataforma.
<li>Es responsabilidad del Comprador, por su parte y de previo a colocar su Orden, revisar todas las especificidades (e.g. fecha y hora prevista; lugar, ubicación; y naturaleza, entre otros). De equivocarse el Comprador y/o de requerir algún cambio, deberá asumir las consecuencias que de su error deriven, ya que no hay garantía alguna de que la Orden se pueda revertir, ni de que se apruebe ningún tipo de cambio.
<li>El valor de los productos y servicios de SAICOR, es definido por SAICOR, los precios por productos y servicios que comercialicen los Usuarios atraves de la Plataforma o con ocasión de esta, es definida por los Usuarios, por tanto, SAICOR no posee las facultades para ejercer descuentos o variaciones en éste, salvo expresa orden de los Usuarios. En caso de variaciones en el precio de productos y/o servicios de los Usuarios publicada a través de la Plataforma, SAICOR no garantiza de ninguna manera la veracidad de la información. 
<li>SAICOR únicamente recibe pagos por medio de transferencia o depósito bancario y pago electrónico con tarjetas de débito o crédito en su Plataforma, dichos pagos se reciben a través de sus “Cobradores”, en ninguna manera se aceptan cheques o pagos en efectivo.
<li>Para que SAICOR acepte su orden, este deberá haber recibido la correspondiente aprobación de parte de la Autorizadora de la tarjeta de crédito o débito o bien confirmado contra transferencia o depósito bancario. Por ende, SAICOR no se hace responsable si dicha institución financiera rechaza la tarjeta de crédito o débito o la transferencia o depósito.
<li>El incumplimiento con el pago a tiempo por productos o servicios de SAICOR, genera de forma automatizada el bloqueo de la plataforma al usuario en las secciones que requiere de pago, no pudiendo utilizar dichas secciones, hasta poner al día el pago por los mismos.
<li>SAICOR se reserva el derecho de aceptación de una orden, aún después de recibida la confirmación.
<li>Cada una de las partes (e.g. Usuarios y SAICOR) será individualmente responsable por sus propias cargas e impuestos que le sean imponibles con ocasión/en virtud de los Usos relacionados con la Plataforma; así como por presentar debidamente todas las declaraciones, formularios y/o documentación correspondiente a éstas. Así, de conformidad con el ordenamiento jurídico aplicable, si SAICOR se viere compelida por las autoridades correspondientes, a cubrir los impuestos o cargas aplicables a cualquier otra de las partes, podrá recurrir a solicitar de dicha parte, que le reconozca y erogue lo pagado, debiendo la parte requerida, devolver de inmediato los dineros pagados por SAICOR. Sin perjuicio de lo anterior, en ningún caso, ni en ningún momento SAICOR se hará responsable por los impuestos o cargas que corresponda pagar a los Usuarios en virtud de las ganancias que pueda derivar de la venta de productos y/o servicios; ni por aquellos que corresponda cubrir a los Cobradores.
</ul>
<h5><b>6. Del tratamiento de los datos de los Usuarios</b></h5>
<ul>
<li>SAICOR no solicita de ninguna forma, ni por ningún medio induce u obliga a sus Usuarios, a brindar "Datos Sensibles" (i.e. información relativa al fuero íntimo de la persona, como por ejemplo los que revelen origen racial, opiniones políticas, convicciones religiosas, espirituales, estrato social, información biomédica o genética, vida y orientación sexual), por ende, si el Usuario decide voluntariamente y por su propia cuenta y riesgo, brindar dicha información o ingresarla a la Plataforma, lo hace bajo su propia responsabilidad, en el entendido que tal información no es necesaria, ni requerida para ninguno de los efectos previstos por SAICOR.
<li>Sin perjuicio de lo anterior, SAICOR podrá solicitar información del Usuario (en adelante la "InfoU") cuando así lo requiera para el desarrollo de los Usos previstos de la Plataforma, y aquellos otros establecidos en los TyC vigentes, y sus reformas. La InfoU será usada para efectos internos de SAICOR .
<li>La administración de la InfoU que SAICOR pudiera solicitar durante todo su ciclo de manejo (desde el ingreso de la misma a la Plataforma, hasta su egreso o destrucción, cuando ello corresponda), se llevará a cabo de conformidad con las exigencias de tratamiento de dichos datos, impuestas por el ordenamiento jurídico aplicable.
<li>La InfoU que SAICOR incluye e ingresa a sus sistemas y bases de datos es la brindada por el Usuario mismo, en su registro a la Plataforma y aquella otra que el ordenamiento jurídico permita incorporar sin violentar sus normas.
<li>En el respectivo registro que SAICOR pone a disposición de sus Usuarios (en adelante el "Registro") existen requerimientos de información que son de carácter obligatorio (marcados con asterisco) y otros que son potestativos. Para realizar efectivamente el Registro, el Usuario deberá proceder a completar los espacios obligatorios, en el entendido que de no hacerlo, no quedará registrado en la Plataforma y por ende, no podrá proceder a realizar ninguna de las acciones para las cuales el Registro es requisito indispensable.
<li>La InfoU será procesada por SAICOR, de acuerdo a las políticas y estándares de seguridad adoptados por ésta, mismos que son concordantes con mejores prácticas internacionalmente reconocidas y aplicables a la materia. SAICOR se compromete a que, de compartir InfoU con sus Aliados de Negocio, procederá a advertirles previamente a éstos, de la obligación que ellos han de asumir a su vez, de proveer un nivel de seguridad no menor al que SAICOR ha adoptado para el cuido y resguardo de la información. Cuando SAICOR así lo estime conveniente, dispondrá incluso, la firma de sendos acuerdos de confidencialidad con dichos Aliados de Negocio.
<li>En cualquier momento que el Usuario se entere que su Información presenta errores, imprecisiones, incorrecciones, faltas de completitud o carezca de integridad; así como cuando éste tome la determinación de que la misma sea eliminada de la Plataforma y/o de los sistemas de SAICOR, podrá proceder a contactar al Tutor de la Información a la siguiente dirección legal@saicor.co.cr para solicitarle la rectificación, aclaración o supresión de su InfoU, lo cual se hará en el plazo de ley. El Usuario entiende y acepta que su eventual requerimiento en este sentido, no tiene efecto retroactivo; y que el mismo no aplica para transacciones o negociaciones que estén en proceso, entre el Usuario y SAIOCR, mientras éstas no hayan terminado de concretarse.
</ul>
<h5><b>7. Exención de responsabilidad</b></h5>
<ul>
<li>A pesar que SAICOR realiza su mejor esfuerzo para mantener la Plataforma operando de manera óptima y dentro de elevados estándares operativos y de seguridad, no puede y de hecho no lo hace, garantizar que sus sistemas y/o la Plataforma misma, funcionen o se mantengan libres de errores, interrupciones no deseadas, intrusiones de terceros, intercepciones ajenas y/o instrucciones o códigos maliciosos. El Usuario entiende y acepta que ningún sistema informático o de información es infalible y que por ende, no es razonable, ni posible, ofrecer o brindar un grado absoluto de seguridad, ni de operación libre de fallas.
<li>Asimismo, el Usuario entiende y acepta que la mayor parte de los contenidos ingresados en la Plataforma provienen de terceros ajenos a SAICOR y que si bien SAICOR ha instaurado sistemas internos que le permiten llevar a cabo cierto tipo de auditorías, e instaurar controles, SAICOR no puede garantizar y de hecho no lo hace, que su Plataforma vaya a encontrarse libre de imprecisiones, falsedades, errores, conductas u omisiones culposas y/o dolosas capaces de causar daño. El Usuario entiende y acepta que cualquier acción u omisión de un tercero ajeno a SAICOR es responsabilidad de dicho tercero y nunca de SAICOR.
<li>Dado que hay muchos actores y factores (internos y/o externos) involucrados en la consecución de un resultado, SAICOR no garantiza ningún resultado en particular en el uso de la Plataforma, incluyendo pero sin limitarse éstos a; venta de vehículos; cumplimiento de los productos y/o servicios ofrecidos por Usuarios; números o porcentajes, nivel de utilidades y/o ganancias; realización efectiva de actividades comerciales entre Usuarios; calidad de los mismos; y/o efectividad de la ventana publicitaria, entre otros.
<li>El Usuario acepta pues la Plataforma tal y como está, según la disponibilidad que ésta tenga y a su propio riesgo, con los contenidos, Usos y particularidades que le son propios. SAICOR no hace ninguna promesa o garantía diferente a las que expresamente y por escrito, están contenidas en estos TyC vigentes y por ende, ninguna podrá asumirse como implícita tampoco.
<li>EN VIRTUD DE LO ANTERIOR, EL USUARIO ENTIENDE Y ACEPTA TAMBIÉN, QUE EN NINGÚN CASO SAICOR SERÁ RESPONSABLE POR DAÑOS DIRECTOS, INDIRECTOS, ESPECIALES, INCIDENTALES O CONSECUENTES, DE CUALESQUIER ÍNDOLE, INCLUYENDO PERO SIN LIMITARSE ÉSTOS A PÉRDIDAS DE UTILIDADES, PÉRDIDAS DE OPORTUNIDADES DE NEGOCIO, DAÑOS EN EQUIPOS Y/O SISTEMAS, CAUSADOS Y/O ACAECIDOS EN VIRTUD DEL USO, IMPOSIBILIDAD DE USO Y/O FALLA DE LA PLATAFORMA; NI POR LA COMPLETITUD Y/O VERACIDAD, O FALTA DE LAS MISMAS, EN/DE LOS CONTENIDOS EN ELLA INCORPORADOS; NI POR DEFECTOS Y/O EXCESOS EN EL PROCESAMIENTO DE PAGOS; PAGOS NO REALIZADOS; DEVOLUCIONES RETENIDAS POR TERCEROS; O NO REALIZADAS Y/O NINGÚN TIPO DE NEGOCIACIONES FALLIDAS. ASIMISMO, EL USUARIO ENTIENDE Y ACEPTA QUE SAICOR NO SE HACE RESPONSABLE POR LA PRESTACION DE LOS SERVICIOS O RETARDO EN LA PRESTACION DE LOS MISMOS QUE ÉSTE SUFRA EN EL USO DE LA PLATAFORMA, TODO ELLO AUN Y CUANDO SAICOR HUBIESE SIDO AVISADA O HAYA TENIDO CONOCIMIENTO SOBRE LA POSIBILIDAD DE QUE SE DIERAN TALES DAÑOS O CIRCUNSTANCIAS INCONVENIENTES O ADVERSAS.
<li>Sin perjuicio de lo anterior, SAICOR se compromete a realizar su mejor esfuerzo para atender las preocupaciones o problemas que pudiesen generarse con ocasión/en virtud del uso de la Plataforma y para ello pone a disposición la siguiente dirección: servicoalcliente@saicor.co.cr con el fin de que el Usuario pueda comunicarle sus inquietudes. El Usuario entiende y acepta, eso sí, que las acciones que pueda SAICOR efectivamente tomar a este respecto, dependerán del propio criterio de SAICOR y de sus posibilidades dependiendo del caso de que se trate.
<li>SAICOR no se hace responsable en ningún caso, por circunstancias adversas que puedan ocurrir, incluyendo, pero sin limitarse éstos a: incumplimientos en negociaciones o relaciones comerciales entre los Usuarios y/o terceras personas.
</ul>
<h5><b>8. Sitios de Terceros</b></h5>
<ul>
<li>El Usuario entiende y acepta que: i) SAICOR no tiene ningún control sobre los sitios Web, sistemas, aplicaciones y/o plataformas de terceros (en adelante "Sitios de Terceros"), a los que éste ingrese en virtud de cualquier vínculo contenido o habilitado en la Plataforma (incluidos entre ellos, pero sin limitarse éstos a links; hyperlinks; banners; botones o herramientas de búsqueda de la WWW, entre otros) (en adelante los "Vínculos"); ii) Que dichos Sitios de Terceros, no son propiedad de SAICOR, no son operados, protegidos, ni dirigidos por ésta y que por ende, SAICOR no asume responsabilidad alguna con respecto a sus contenidos, políticas y/o estándares de seguridad, ni responde por las prácticas ejercidas por sus dueños u operadores. Al redirigirse a los Sitios de Terceros, el Usuario libera de toda responsabilidad a SAICOR, por las consecuencias de su actividad o inactividad en ellos, así como por las consecuencias que puedan derivarse de éstas.
<li>Sin perjuicio alguno de lo anterior, SAICOR se reserva el derecho a retirar, de manera unilateral y sin previo aviso, los Vínculos con Sitios de Terceros incluidos en la Plataforma, cuando lo considere conveniente y a su propia discreción.
</ul>
<h5><b>9. De las garantías y representaciones del Usuario</b></h5>
<ul>
El Usuario le garantiza a SAICOR que:
<li>Es mayor de 18 años de edad para el uso de la Plataforma
<li>Posee la capacidad jurídica, legal y personal de obligarse en los extremos y alcances que lo requieren los presentes TyC y el ordenamiento jurídico, así como para tomar las decisiones y asumir las responsabilidades involucradas en el Uso de la Plataforma;
<li>Se obliga a respetar los TyC vigentes, y a obedecer lo estipulado por el ordenamiento jurídico aplicable;
<li>No utilizará la Plataforma como medio, objeto y/o fin de ilícitos o delitos;
<li>La información que ingresa y/o postea en la Plataforma, y en los Sitios de Terceros involucrados es legal, actual, veraz, exacta, y adecuada, y se compromete a tenerla debidamente actualizada por todo el tiempo que sea necesario, en virtud de los Usos de la Plataforma;
<li>No hará representaciones a nombre de SAICOR, que no estén debidamente autorizadas de previo y por escrito por SAICOR; y
<li>No violentará derechos de propiedad intelectual, marcas, patentes, derechos de autor, secretos comerciales, industriales ni otros derechos conexos o relacionados de SAICOR, ni de terceros.
1.  Notificación de reclamos ante violaciones contra los derechos de Propiedad Intelectual
<li>De ser el Usuario el dueño o representante autorizado de derechos de propiedad intelectual que estima están siendo violentados en la Plataforma, se le agradecerá nos envíe el reclamo correspondiente a la siguiente dirección legal@saicor.co.cr, a fin de que podamos contactarlo, y tomar las medidas que estimemos convenientes.

<li>El reclamo en este sentido, deberá incluir indicación del nombre, calidades y datos de contacto de quién lo hace; su relación con la obra protegida; las pruebas que tenga para fundamentar su dicho y cualquier otra información que estime pertinente.
</ul>
<br>
<h5><b>10. De los contenidos ingresados y/o posteados en SAICOR</b></h5>
<br>
<ul>
<li>A menos que hayan sido ingresados y/o posteados directamente por SAICOR, todos los contenidos ingresados o posteados, son responsabilidad directa e ineludible de la persona a la que pertenezca la cuenta de usuario y/o contraseña de acceso a la Plataforma utilizada para tal fin. Para todo efecto, se presumirá entonces que el Usuario que posteó o generó un determinado contenido, es la persona a la que corresponde dicha cuenta y/o contraseña.
<li>Todo Usuario al que se le hayan asignado contraseñas de acceso para los diferentes sistemas e información de SAICOR, tiene con respecto a éstas, las siguientes obligaciones:
</li>
</ul>
<b>o</b> Debe seguir todas las disposiciones y recomendaciones emitidas por SAICOR, para la elaboración de contraseñas seguras o en su caso, ajustarse a los sistemas de seguridad instaurados por SAICOR para tales efectos;
<br><b>o</b> No debe compartir, prestar, divulgar, transferir, de cualesquier forma o medio, las contraseñas que le han sido asignadas, ni aquellas por las cuales las ha sustituido;
<br><b>o</b> No debe bajo ninguna circunstancia escribirlas en papel, ni almacenarlas sin protección;
<br><b>o</b> Debe seguir todas las disposiciones emitidas por SAICOR, para el cambio regular de contraseñas, cuando ello correspondiere;
<br><b>o</b> Debe cambiar las contraseñas cuando sospeche o tenga la certeza de que las mismas han sido comprometidas o vulneradas;
<br><b>o</b> No debe bajo ninguna circunstancia, utilizar contraseñas que no le han sido asignadas; y
<br><b>o</b> No debe, bajo ninguna circunstancia, intentar descifrar y/o violentar contraseñas de acceso que no le hayan sido asignadas.
<br><b>o</b> Una vez que SAICOR le haya asignado una contraseña de acceso provisional y/o cada vez que se requiera el cambio de éstas, el Usuario debe proceder inmediatamente a elaborar nuevas contraseñas, que cumplan estrictamente con lo establecido por losprocedimientos formalmente aprobados por SAICOR, para tales efectos.
<br>
<h5><b>11. Foro de competencia</b></h5>
<ul>
<li>El Usuario acepta regirse por el ordenamiento jurídico costarricense, en todo lo concerniente y/o relacionado a la Plataforma y/o sus Usos, renunciando expresamente por ende, a cualquier otro foro de competencia aplicable. En este sentido, el Usuario acepta someterse consciente, voluntaria e incondicionalmente a la jurisdicción de los tribunales costarricenses.</li>
<li>En plena conformidad con lo anterior, de existir cualquier diferendo que amerite llevarse a la vía judicial, ello deberá hacerse dentro de la República de Costa Rica.</li>
</ul>
<h5><b>12. Resolución de conflictos</b></h5>
<ul>
<li>En caso de eventualmente tener el Usuario algún reclamo que realizarle a SAICOR, éste se obliga a plantearlo en primera instancia a través de la vía amistosa, entendida esta como la comunicación formal debidamente documentada y justificada de su posición y/o molestia, presentada por medio de mensaje de correo electrónico a la siguiente dirección legal@saicor.co.cr. Una vez recibida esta comunicación, SAICOR dentro de un plazo no mayor a quince días hábiles (salvo que por ley se defina obligatoriamente uno menor), se pronunciará sobre la procedencia o no del reclamo, solicitará mayor información y/o contactará al Usuario para lo que corresponda, a fin de tratar de encontrar una salida pacífica al problema. De no lograrse la resolución del conflicto por la vía amistosa, pasados treinta días hábiles a partir del recibo de la comunicación por SAICOR, el Usuario podrá, si así lo tiene a bien, acudir a los tribunales de justicia costarricenses a plantear su reclamo.</li>
</ul>
<h5><b>13. Idioma prevalente</b></h5>
<ul>
<li>Los presentes TyC han sido redactados teniendo el idioma español, como idioma oficial y predominante. Cualquier traducción de los mismos a otros idiomas, se hace en consideración a Usuarios que pudiesen no entender el español. Sin embargo, ha de tenerse presente que si por cuestiones de traducción, llegare a existir alguna diferencia entre la versión de los TyC en español (en adelante "Versión Oficial") y aquellos traducidos a otros idiomas, la que prevalecerá en todos los casos es la Versión Oficial. Por ende, ante cualquier duda o disenso, se aclara que estos TyC han de ser interpretados y aplicados, conforme la a la Versión Oficial.</li>
</ul>
<h5><b>14. Supervivencia de los TyC como un todo</b></h5>
<ul>
<li>Si alguna cláusula de los TyC llegara a ser debidamente declarada por las autoridades correspondientes como inválida, ilegal o inaplicable, ésta se tendrá por no puesta, empero la validez, legalidad y la aplicabilidad de las cláusulas restantes no se verá afectada de ninguna forma.</li>
</ul>
</section>